### ISSUE TITLE
Save stopped working

### ISSUE THREAD

**Issue by zugmana** [ME-ICA/rica#61]
Hi,

I've been using rica through (https://rica-fmri.netlify.app/) and since yesterday the "save" function seems to have stopped working.
everything else in the website works fine except for that. 
I'm using chrome Version 112.0.5615.137.  I've also tried on firefox 102.10.0esr.
Any ideas what might be causing it? 
Many thanks!

**Comment by zugmana** [comment]
ps: Tried running locally and when hitting save I get the error below

"""
ERROR
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes')
    at Plots.saveManualClassification (http://localhost:3000/static/js/bundle.js:1240:88)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:54552:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:54596:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:54651:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:54665:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:58287:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:58313:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:58324:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:58333:7)
    at http://localhost:3000/static/js/bundle.js:58511:16
ERROR
Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes')
    at Plots.saveManualClassification (http://localhost:3000/static/js/bundle.js:1240:88)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:54552:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:54596:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:54651:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:54665:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:58287:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:58313:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:58324:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:58333:7)
    at http://localhost:3000/static/js/bundle.js:58511:16
"""

**Comment by eurunuela** [comment]
Hi @zugmana!

First of all, thank you for using Rica!

What version of Rica are you using? You should see the version on the bottom right corner of the About pop-up card.

If it says `v1.1.0`, you're on the latest version.

I have just tried saving the files using Arc (chromium-based) and Safari, and it worked fine.

If you actually are in this version, what does the console show? You can see the error messages by clicking on "View" -> "Developer" -> "Javascript Console".

**Comment by zugmana** [comment]
Here's the console log:
"""
main.d9514865.js:2 Reading data...
main.d9514865.js:2 Array(6)
main.d9514865.js:2 Data read into dictionary.
main.d9514865.js:2 Array(6)
main.d9514865.js:2 Array(1)
main.d9514865.js:2 Array(43)
main.d9514865.js:2 Array(4)
main.d9514865.js:2 Array(2)
main.d9514865.js:2 Array(1)0: (43) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]length: 1[[Prototype]]: Array(0)
main.d9514865.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at r.value (main.d9514865.js:2:589383)
    at Object.Ke (main.d9514865.js:2:86539)
    at Ye (main.d9514865.js:2:86693)
    at main.d9514865.js:2:104918
    at Or (main.d9514865.js:2:105012)
    at Pr (main.d9514865.js:2:105427)
    at main.d9514865.js:2:111075
    at Le (main.d9514865.js:2:186796)
    at main.d9514865.js:2:106895
    at Dr (main.d9514865.js:2:106925)
main.d9514865.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at r.value (main.d9514865.js:2:589383)
    at Object.Ke (main.d9514865.js:2:86539)
    at Ye (main.d9514865.js:2:86693)
    at main.d9514865.js:2:104918
    at Or (main.d9514865.js:2:105012)
    at Pr (main.d9514865.js:2:105427)
    at main.d9514865.js:2:111075
    at Le (main.d9514865.js:2:186796)
    at main.d9514865.js:2:106895
    at Dr (main.d9514865.js:2:106925)
main.d9514865.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at r.value (main.d9514865.js:2:589383)
    at Object.Ke (main.d9514865.js:2:86539)
    at Ye (main.d9514865.js:2:86693)
    at main.d9514865.js:2:104918
    at Or (main.d9514865.js:2:105012)
    at Pr (main.d9514865.js:2:105427)
    at main.d9514865.js:2:111075
    at Le (main.d9514865.js:2:186796)
    at main.d9514865.js:2:106895
    at Dr (main.d9514865.js:2:106925)
main.d9514865.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at r.value (main.d9514865.js:2:589383)
    at Object.Ke (main.d9514865.js:2:86539)
    at Ye (main.d9514865.js:2:86693)
    at main.d9514865.js:2:104918
    at Or (main.d9514865.js:2:105012)
    at Pr (main.d9514865.js:2:105427)
    at main.d9514865.js:2:111075
    at Le (main.d9514865.js:2:186796)
    at main.d9514865.js:2:106895
    at Dr (main.d9514865.js:2:106925)
"""

**Comment by handwerkerd** [comment]
I also looked into this. I think the issue is RICA is now looking for `classification_tags` and failing on datasets that don't yet save that column in the dataframe. I think you'll need some logic to handle old & new tedana formats.

**Comment by eurunuela** [comment]
Thank you @handwerkerd.

I'm at a conference until the end of the week, but I will try to get this fixed today.

**Comment by eurunuela** [comment]
Hey @zugmana, I just opened a pull request that should fix your issue.

Could you please try the following link and let me know if that works?

https://deploy-preview-62--rica-fmri.netlify.app/

**Comment by zugmana** [comment]
Still the same...


"""
main.48b06027.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at r.value (main.48b06027.js:2:589424)
    at Object.Ke (main.48b06027.js:2:86539)
    at Ye (main.48b06027.js:2:86693)
    at main.48b06027.js:2:104918
    at Or (main.48b06027.js:2:105012)
    at Pr (main.48b06027.js:2:105427)
    at main.48b06027.js:2:111075
    at Le (main.48b06027.js:2:186796)
    at main.48b06027.js:2:106895
    at Dr (main.48b06027.js:2:106925)

**Comment by eurunuela** [comment]
Done! Could you please try now?

**Comment by eurunuela** [comment]
Thank you @zugmana for spotting it and opening the issue! 🙏
